### ISSUE TITLE
ch.tutteli.gradle.plugins.spek does not support Kotlin 1.7+

### ISSUE THREAD

**Issue by vlsi** [robstoll/tutteli-gradle-plugins#211]
Here's a stacktrace:

```
        groovy.lang.MissingMethodException: No signature of method:
org.jetbrains.kotlin.gradle.plugin.KotlinPluginWrapper.getKotlinPluginVersion() is applicable for argument types: () values: []
            at ch.tutteli.gradle.plugins.spek.SpekPlugin.getKotlinVersion(SpekPlugin.groovy:77)
            at ch.tutteli.gradle.plugins.spek.SpekPlugin.configureForJvm(SpekPlugin.groovy:44)
            at ch.tutteli.gradle.plugins.spek.SpekPlugin$_apply_closure2.doCall(SpekPlugin.groovy:37)
```

**Comment by robstoll** [comment]
Thanks for the report
